server:
  port: 8900

spring:
  application:
    name: xht-lease-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.134:3306/lease?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021$$
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 192.168.213.134
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

minio:
  endpoint: http://192.168.213.134:9001
  access-key: root
  secret-key: yzd2021$$
  bucket-name: xht-lease

springdoc:
  default-flat-param-object: true

